language: java

dist: precise

cache:
  directories:
  - ~/.m2
  - ~/.sonar/cache

matrix:
  include:
    - jdk: oraclejdk7
      # coding standard
      script: mvn clean test checkstyle:check

    - jdk: openjdk7
      # use 'verify' phrase to execute integration tests
      # run integration test only one due the the Google quota limitation
      script: mvn clean verify

    - jdk: oraclejdk8
      # only tests
      script: mvn clean test

    - jdk: oraclejdk8
      script:
        - # sonar-scanner, commented, as I don't have a token for the sonarqube integration

after_success:
  # push report to codecov server
  bash <(curl -s https://codecov.io/bash)

